/**
 * AUTO-GENERATED by scripts/parse-references.mjs from the live Wikipedia
 * wikitext — do not hand-edit; regenerate instead.
 * Citations appear in article order (119 unique; 62 additional in-text reuses).
 */
export interface Reference {
  title: string
  url: string
  work: string
  date: string
  accessDate: string
}

export const references: Reference[] = [
  {
    "title": "About PM Cares Fund",
    "url": "https://pmcares.gov.in/en/web/page/about_us",
    "work": "",
    "date": "",
    "accessDate": ""
  },
  {
    "title": "Govt appoints Ratan Tata, 2 others as trustees of PM CARES Fund",
    "url": "https://www.livemint.com/news/india/govt-appoints-ratan-tata-2-others-as-trustees-of-pm-cares-fund-11663746503305.html",
    "work": "",
    "date": "",
    "accessDate": ""
  },
  {
    "title": "How different is the PM CARES Fund from the PM's National Relief Fund?",
    "url": "https://www.thehindu.com/news/national/coronavirus-how-different-is-the-pm-cares-fund-from-the-pms-national-relief-fund/article31546287.ece",
    "work": "The Hindu",
    "date": "2020-05-10",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Fund - PM's Citizen Assistance & Relief in Emergency Situations Fund",
    "url": "https://www.pmcares.gov.in/",
    "work": "www.pmcares.gov.in",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM-CARES Public Or Private Fund? Documents Reveal Contradiction",
    "url": "https://www.ndtv.com/india-news/pm-cares-public-or-private-fund-document-reveal-contradiction-2339381",
    "work": "NDTV.com",
    "date": "",
    "accessDate": "2020-12-18"
  },
  {
    "title": "'PM CARES not a public authority under RTI Act': PMO rejects application seeking fund details; will appeal, says law student",
    "url": "https://www.firstpost.com/india/pm-cares-not-a-public-authority-under-rti-act-pmo-rejects-application-seeking-fund-details-will-appeal-says-law-student-8430551.html",
    "work": "Firstpost",
    "date": "2020-05-31",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Got Rs 6,500 Cr A Month Ago, Allocates Rs 3,100 Cr To COVID-19 Fight Now",
    "url": "https://www.huffingtonpost.in/entry/pm-cares-fund-allocation_in_5ebcb8b6c5b6c498dde75593",
    "work": "HuffPost India",
    "date": "2020-05-14",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM-CARES fund to have up to 13 eminent experts",
    "url": "https://economictimes.indiatimes.com/news/politics-and-nation/pm-cares-fund-to-have-up-to-13-eminent-experts/articleshow/74956414.cms",
    "work": "The Economic Times",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM Modi didn't seek cabinet nod to set up PM CARES Fund: RTI reply",
    "url": "https://www.theweek.in/news/india/2020/08/20/pm-modi-didnt-care-to-seek-cabinet-nod-to-set-up-pm-cares-fund-rti-reply.html",
    "work": "The Week",
    "date": "",
    "accessDate": "2020-08-22"
  },
  {
    "title": "PM-CARES Public Or Private Fund? Documents Reveal Contradiction",
    "url": "https://www.ndtv.com/india-news/pm-cares-public-or-private-fund-document-reveal-contradiction-2339381",
    "work": "NDTV.com",
    "date": "",
    "accessDate": "2020-12-25"
  },
  {
    "title": "PM CARES: Petition questions use of national emblem for a non-govt entity",
    "url": "https://english.madhyamam.com/india/pm-cares-use-of-national-emblem-officials-for-a-non-govt-entity-questioned-620009",
    "work": "english.madhyamam.com",
    "date": "2020-12-17",
    "accessDate": "2020-12-18"
  },
  {
    "title": "PM-CARES — Centre sends conflicting signals on foreign donations",
    "url": "https://www.thehindu.com/news/national/pm-cares-centre-sends-conflicting-signals-on-foreign-donations/article31245203.ece",
    "work": "The Hindu",
    "date": "2020-04-03",
    "accessDate": "2020-07-30"
  },
  {
    "title": "New Delhi to accept foreign aid to deal with covid-19 pandemic crisis",
    "url": "https://www.livemint.com/news/india/covid-19-india-decides-to-accept-foreign-aid-to-deal-with-pandemic-crisis-11585748039556.html",
    "work": "Livemint",
    "date": "2020-04-01",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Coronavirus: Govt to accept foreign contribution to PM-CARES fund",
    "url": "https://indianexpress.com/article/india/coronavirus-govt-to-accept-foreign-contribution-to-pm-cares-fund-6342876/",
    "work": "The Indian Express",
    "date": "2020-04-02",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM-CARES to be audited by independent auditors",
    "url": "https://economictimes.indiatimes.com/news/politics-and-nation/pm-cares-to-be-audited-by-independent-auditors/articleshow/75112792.cms?from=mdr",
    "work": "The Economic Times",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Fund gets FCRA exemption without meeting pre-condition of CAG audit",
    "url": "https://www.thehindu.com/news/national/pm-cares-fund-gets-fcra-exemption-without-meeting-pre-condition-of-cag-audit/article32584371.ece",
    "work": "The Hindu",
    "date": "2020-09-11",
    "accessDate": "2020-09-15"
  },
  {
    "title": "Donation to PM CARES Fund to be fully exempted section 80G of I-T Act",
    "url": "https://www.thehindubusinessline.com/economy/policy/donation-to-pm-cares-fund-to-be-fully-exempted-under-income-tax-act/article31221733.ece",
    "work": "The Hindu @businessline",
    "date": "31 March 2020",
    "accessDate": "2020-04-01"
  },
  {
    "title": "Govt clarifies on company's contributions to PM CARES Fund above CSR limit",
    "url": "https://economictimes.indiatimes.com/news/economy/policy/govt-clarifies-on-companys-contributions-to-pm-cares-fund-above-csr-limit/articleshow/74907220.cms",
    "work": "The Economic Times",
    "date": "2020-03-31",
    "accessDate": "2020-03-31"
  },
  {
    "title": "Ordinance issued to make PM CARES donations tax free",
    "url": "https://economictimes.indiatimes.com/news/politics-and-nation/ordinance-issued-to-make-pm-cares-donations-tax-free/articleshow/74923420.cms",
    "work": "The Economic Times",
    "date": "2020-04-01",
    "accessDate": "2020-04-01"
  },
  {
    "title": "Centre set up PM CARES, indicates memo",
    "url": "https://www.thehindu.com/news/national/centre-set-up-pm-cares-indicates-memo/article32396972.ece",
    "work": "The Hindu",
    "date": "2020-08-20",
    "accessDate": "2020-08-22"
  },
  {
    "title": "RTI activists question Centre's decision to put PM CARES Fund in Companies Act for CSR eligibility",
    "url": "https://timesofindia.indiatimes.com/india/rti-activists-question-centres-decision-to-put-pm-cares-fund-in-companies-act-for-csr-eligibility/articleshow/77685797.cms",
    "work": "The Times of India",
    "date": "22 August 2020",
    "accessDate": "2020-08-22"
  },
  {
    "title": "EXCLUSIVE: Modi Advisor's Letter Undermines PMO Claim That PM CARES Isn't Covered By RTI",
    "url": "https://www.huffingtonpost.in/entry/narendra-modi-pmcares-pmo-rti-transparency_in_5f4bd23fc5b697186e377fac",
    "work": "HuffPost India",
    "date": "2020-08-31",
    "accessDate": "2020-08-31"
  },
  {
    "title": "Donations to PM CARES allowed under CSR, but not to states or CMs: Corporate ministry",
    "url": "https://theprint.in/india/donations-to-pm-cares-allowed-under-csr-but-not-to-states-or-cms-corporate-ministry/399984/",
    "work": "The Print",
    "date": "11 April 2020",
    "accessDate": ""
  },
  {
    "title": "Congress questions setting up of PM CARES Fund to deal with coronavirus",
    "url": "https://www.thehindu.com/news/national/congress-questions-setting-up-of-pm-cares-fund-to-deal-with-coronavirus/article31210904.ece",
    "work": "The Hindu",
    "date": "2020-03-30",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Why PM CARES Fund when there is PMNRF, asks CPI(M) MP",
    "url": "https://www.thehindu.com/news/national/why-pm-cares-fund-when-there-is-pmnrf-asks-cpim-mp/article31237778.ece",
    "work": "The Hindu",
    "date": "2020-04-02",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Fund Won't Be Checked By Government's Auditor, Say Sources",
    "url": "https://www.ndtv.com/india-news/coronavirus-pm-cares-fund-wont-be-checked-by-cag-say-sources-2217714",
    "work": "NDTV",
    "date": "24 April 2020",
    "accessDate": "2020-04-25"
  },
  {
    "title": "Prime Minister's National Relief Fund",
    "url": "https://pmnrf.gov.in/en/about",
    "work": "pmnrf.gov.in",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES And PMNRF Both Opaque In Same Way, Documents Show",
    "url": "https://www.huffingtonpost.in/entry/pm-cares-and-pmnrf-both-opaque-in-same-way-documents-show_in_5e8cbd55c5b6e1d10a6ad2c9",
    "work": "HuffPost India",
    "date": "2020-04-08",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Fund better suited to deal with coronavirus crisis, say legal experts",
    "url": "https://www.businesstoday.in/current/economy-politics/pm-cares-fund-better-suited-tto-deal-with-coronavirus-crisis-say-legal-experts/story/399670.html",
    "work": "www.businesstoday.in",
    "date": "31 March 2020",
    "accessDate": "2020-03-31"
  },
  {
    "title": "Narendra Modi announces new fund for people to donate towards govt fight against coronavirus",
    "url": "https://www.businessinsider.in/india/news/narendra-modi-announces-new-fund-pmcares-for-people-to-donate-towards-govt-fight-against-coronavirus/articleshow/74863818.cms",
    "work": "Business Insider",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM-CARES Got Rs 3,076 Crore In 5 Days; P Chidambaram Says Name Donors",
    "url": "https://www.ndtv.com/india-news/pm-cares-got-rs-3-076-crore-in-5-days-p-chidambaram-says-name-donors-2289104",
    "work": "NDTV.com",
    "date": "",
    "accessDate": "2020-09-11"
  },
  {
    "title": "Receipts and Payments Account for the period ending March 31st, 2020",
    "url": "https://www.pmcares.gov.in/assets/donation/pdf/Audited%20Statement.PDF",
    "work": "PM CARES Fund",
    "date": "7 September 2020",
    "accessDate": "11 September 2020"
  },
  {
    "title": "PM CARES Fund - PM's Citizen Assistance & Relief in Emergency Situations Fund",
    "url": "https://www.pmcares.gov.in/en/web/page/about_us",
    "work": "",
    "date": "",
    "accessDate": ""
  },
  {
    "title": "PM Cares Fund Collection: PM-CARES corpus crosses $1 billion",
    "url": "https://timesofindia.indiatimes.com/india/pm-cares-corpus-crosses-1-billion/articleshow/75830605.cms",
    "work": "The Times of India",
    "date": "19 May 2020",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Cyber chief's warning as hackers target PM's Covid fund",
    "url": "https://economictimes.indiatimes.com/tech/internet/cyber-chiefs-warning-as-hackers-target-pms-covid-fund/articleshow/74877953.cms",
    "work": "The Economic Times",
    "date": "2020-03-29",
    "accessDate": "2020-03-30"
  },
  {
    "title": "Here Is List Of Celebrities, Corporates And Ministers Who Donated To Fight Coronavirus",
    "url": "https://www.outlookindia.com/website/story/india-news-heres-a-list-of-celebrities-corporates-and-ministers-donate-to-fight-coronavirus/349718",
    "work": "Outlook India",
    "date": "April 2020",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Here's how India Inc is contributing in fight against coronavirus pandemic",
    "url": "https://indianexpress.com/article/coronavirus/heres-how-india-inc-is-contributing-in-fight-against-coronavirus-pandemic-6337472/",
    "work": "The Indian Express",
    "date": "2020-04-01",
    "accessDate": "2020-07-30"
  },
  {
    "title": "BCCI contributes 51 crores to PM Cares fund in fight against coronavirus",
    "url": "https://indianexpress.com/article/sports/cricket/bcci-to-contribute-51-crores-to-prime-ministers-pm-cares-fund-coronavirus-covid-19-6336357/",
    "work": "The Indian Express",
    "date": "2020-03-28",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Hockey India donate additional Rs 75 lakhs to PM-CARES Fund, golfer Anirban Lahiri pledges Rs 7 lakhs",
    "url": "https://indianexpress.com/article/sports/sport-others/hockey-india-donates-rs-75-lakhs-more-to-pm-cares-fund-golfer-lahiri-pledges-rs-7-lakhs-6347255/",
    "work": "The Indian Express",
    "date": "2020-04-04",
    "accessDate": "2020-07-30"
  },
  {
    "title": "CDS Bipin Rawat to donate Rs 50,000 every month for 1 year to PM-CARES fund",
    "url": "https://indianexpress.com/article/india/cds-bipin-rawat-to-donate-rs-50000-every-month-for-1-year-to-pm-cares-fund-6425083/",
    "work": "The Indian Express",
    "date": "2020-05-24",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Coronavirus — President, V-P to donate a month's salary to PM-CARES Fund",
    "url": "https://www.thehindu.com/news/national/coronavirus-president-v-p-to-donate-a-months-salary-to-pm-cares-fund/article31201652.ece",
    "work": "The Hindu",
    "date": "2020-03-30",
    "accessDate": "2020-07-30"
  },
  {
    "title": "EPFO employees contribute ₹2.5 crore to PM CARES",
    "url": "https://www.thehindu.com/news/national/epfo-employees-contribute-25-crore-to-pm-cares/article31494787.ece",
    "work": "The Hindu",
    "date": "2020-05-03",
    "accessDate": "2020-07-30"
  },
  {
    "title": "L&T announces Rs 150 crore donation to PM-CARES Fund to fight coronavirus",
    "url": "https://indianexpress.com/article/business/companies/lt-announces-rs-150-crore-donation-to-pm-cares-fund-to-fight-coronavirus-covid-19-6338376/",
    "work": "The Indian Express",
    "date": "2020-03-30",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Wipro, Azim Premji Foundation commit ₹1,125 crore to tackle COVID-19 crisis",
    "url": "https://www.thehindu.com/business/Industry/wipro-azim-premji-foundation-commit-1125-crore-to-tackle-covid-19-crisis/article31225092.ece",
    "work": "The Hindu",
    "date": "2020-04-01",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Coronavirus: Akshay Kumar donates Rs 25 crore to PM-CARES Fund",
    "url": "https://indianexpress.com/article/entertainment/bollywood/coronavirus-akshay-kumar-donates-rs-25-crore-to-pm-cares-fund-6336280/",
    "work": "The Indian Express",
    "date": "2020-03-28",
    "accessDate": "2020-07-30"
  },
  {
    "title": "SRK offers 4-storey space to authorities for quarantine purpose, Deepika-Ranveer donate to PM-CARES Fund",
    "url": "https://indianexpress.com/article/entertainment/bollywood/coronavirus-relief-shah-rukh-khan-quarantine-office-space-deepika-padukone-ranveer-singh-pm-cares-fund-6347007/",
    "work": "The Indian Express",
    "date": "2020-04-04",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Karan Johar's Dharma Productions to donate to PM-CARES, Maharashtra CM relief funds and NGOs",
    "url": "https://indianexpress.com/article/entertainment/bollywood/karan-johar-dharma-productions-to-donate-to-pm-cares-maharashtra-cm-relief-funds-and-ngos-6368160/",
    "work": "The Indian Express",
    "date": "2020-04-18",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Coronavirus — Russian arms firm to donate $2 million to PM CARES Fund",
    "url": "https://www.thehindu.com/news/national/russian-arms-firm-to-donate-2-mn-to-pm-cares-fund/article31350622.ece",
    "work": "The Hindu",
    "date": "2020-04-15",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Indian missions didn't approach any potential donor for PM-CARES in Islamabad, Beijing: RTI",
    "url": "https://www.deccanherald.com/national/indian-missions-didn-t-approach-any-potential-donor-for-pm-cares-in-islamabad-beijing-rti-940147.html",
    "work": "Deccan Herald",
    "date": "2021-01-17",
    "accessDate": "2021-01-18"
  },
  {
    "title": "Maharatnas to navratnas: 38 PSUs give Rs 2,105 crore from CSR to PM CARES",
    "url": "https://indianexpress.com/article/india/maharatnas-to-navratnas-38-psus-give-rs-2105-crore-from-csr-to-pm-cares-6560452/",
    "work": "The Indian Express",
    "date": "2020-08-19",
    "accessDate": "2020-08-22"
  },
  {
    "title": "101 PSUs give Rs 155 crore from their staff salaries to PM fund",
    "url": "https://indianexpress.com/article/india/101-psus-give-rs-155-crore-from-their-staff-salaries-to-pm-cares-fund-7094510/",
    "work": "The Indian Express",
    "date": "2020-12-07",
    "accessDate": "2020-12-07"
  },
  {
    "title": "From RBI & govt banks to LIC, Rs 205 crore to PM Cares from salaries",
    "url": "https://indianexpress.com/article/india/from-rbi-govt-banks-to-lic-rs-205-crore-to-pm-cares-from-salaries-6618506/",
    "work": "The Indian Express",
    "date": "2020-09-28",
    "accessDate": "2020-10-02"
  },
  {
    "title": "IITs, IIMs, Central universities, Navodaya schools dip into pay for PM Cares",
    "url": "https://indianexpress.com/article/india/iits-iims-central-univs-navodaya-schools-dip-into-pay-for-pm-cares-6605415/",
    "work": "The Indian Express",
    "date": "2020-09-22",
    "accessDate": "2020-10-02"
  },
  {
    "title": "Armed forces gave Rs 203.67 cr from day's salary to PM-CARES Fund",
    "url": "https://indianexpress.com/article/india/armed-forces-gave-rs-203-67-cr-from-days-salary-to-pm-cares-fund-7109235/",
    "work": "The Indian Express",
    "date": "2020-12-18",
    "accessDate": "2020-12-18"
  },
  {
    "title": "No mandatory deduction for donation to PM-CARES: AIIMS admin to RDA",
    "url": "https://www.thehindu.com/news/cities/Delhi/no-mandatory-deduction-for-donation-to-pm-cares-aiims-admin-to-rda/article31353247.ece",
    "work": "The Hindu",
    "date": "2020-04-16",
    "accessDate": "2020-07-30"
  },
  {
    "title": "No Mandatory Deduction for Donation to PM-CARES: AIIMS to RDA",
    "url": "https://www.thequint.com/news/india/no-mandatory-deduction-for-donation-to-pm-cares-aiims-to-rda",
    "work": "TheQuint",
    "date": "2020-04-16",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Doctors at AIIMS, 3 Delhi hospitals say no to pay cut for PM CARES, Safdarjung accepts demand",
    "url": "https://theprint.in/health/doctors-at-aiims-3-delhi-hospitals-say-no-to-pay-cut-for-pm-cares-safdarjung-accepts-demand/400867/",
    "work": "ThePrint",
    "date": "2020-04-13",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Deposit Rs 35,000 to PM-CARES Fund, download Arogya Setu App: Jharkhand HC sets unusual bail conditions",
    "url": "https://indianexpress.com/article/india/jharkhand-hc-bail-pm-cares-fund-coronavirus-lockdown-6367131/",
    "work": "The Indian Express",
    "date": "2020-04-17",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Deposit Rs 1 lakh costs with PM-CARES Fund, says Punjab and Haryana High Court",
    "url": "https://www.tribuneindia.com/news/haryana/deposit-rs1l-costs-with-pm-cares-fund-hc-123575",
    "work": "Tribune India News Service",
    "date": "",
    "accessDate": "2020-08-22"
  },
  {
    "title": "Coronavirus — PM-CARES donations cut from government staff salaries",
    "url": "https://www.thehindu.com/news/national/coronavirus-pm-cares-donations-cut-from-government-staff-salaries/article31383279.ece",
    "work": "The Hindu",
    "date": "2020-04-19",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES and the Paradox of Mandatory Contributions",
    "url": "https://thewire.in/government/pm-cares-revenue-department",
    "work": "The Wire",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "FinMin Tells All Staff, Officers to Donate One Day's Salary Per Month to PM-CARES",
    "url": "https://thewire.in/government/finance-ministry-staff-donation-pm-cares",
    "work": "The Wire",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Modi govt employees irked by pressure to donate to PM CARES Fund to fight Covid-19",
    "url": "https://theprint.in/india/modi-govt-employees-irked-by-pressure-to-donate-to-pm-cares-fund-to-fight-covid-19/404532/",
    "work": "ThePrint",
    "date": "2020-04-19",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Finance Ministry issues modified circular on salary contribution to PM-CARES Fund",
    "url": "https://economictimes.indiatimes.com/news/economy/policy/finance-ministry-issues-modified-circular-on-salary-contribution-to-pm-cares-fund/articleshow/75479765.cms?from=mdr",
    "work": "The Economic Times",
    "date": "",
    "accessDate": "2020-07-23"
  },
  {
    "title": "Staff donate for PMNRF, DU redirects money to PM-CARES",
    "url": "https://www.thehindu.com/news/national/staff-donate-for-pmnrf-du-redirects-money-to-pm-cares/article31390753.ece",
    "work": "The Hindu",
    "date": "2020-04-20",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Fund: All You Need to Know",
    "url": "https://www.dqindia.com/pm-cares-fund-need-know/",
    "work": "DATAQUEST",
    "date": "2020-03-30",
    "accessDate": "2020-03-31"
  },
  {
    "title": "PM Modi announces emergency relief fund for coronavirus fight and for the people",
    "url": "https://economictimes.indiatimes.com/news/politics-and-nation/pm-modi-announces-emergency-relief-fund-for-coronavirus-fight/articleshow/74863297.cms",
    "work": "The Economic Times",
    "date": "2020-03-28",
    "accessDate": "2020-03-31"
  },
  {
    "title": "Secrecy surrounds India PM's '$1bn' Covid-19 fund",
    "url": "https://www.bbc.com/news/world-asia-india-53151308",
    "work": "BBC News",
    "date": "2020-06-30",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Coronavirus — PM CARES makes first allocations",
    "url": "https://www.thehindu.com/news/national/coronavirus-pm-cares-makes-first-allocations/article31576545.ece",
    "work": "The Hindu",
    "date": "2020-05-13",
    "accessDate": "2020-05-15"
  },
  {
    "title": "Rs 3,100 Crore From PM CARES Fund Allocated For Ventilators, Migrants",
    "url": "https://www.ndtv.com/india-news/rs-3-100-crores-from-pm-cares-fund-for-fight-against-coronavirus-says-pms-office-2228336",
    "work": "NDTV",
    "date": "13 May 2020",
    "accessDate": "2020-05-15"
  },
  {
    "title": "Indian Covid-19 vaccine development to be backed by PM-CARES Fund",
    "url": "https://www.hindustantimes.com/india-news/indian-vaccine-development-to-be-backed-by-pm-cares/story-RLUxmlAlPnheClpTLbaSEK.html",
    "work": "Hindustan Times",
    "date": "2020-05-14",
    "accessDate": "2020-05-15"
  },
  {
    "title": "Rs 3,100 crore from PM CARES allocated to buy ventilators, help migrants and develop a vaccine",
    "url": "https://economictimes.indiatimes.com/news/politics-and-nation/rs-3100-crore-from-pm-cares-allocated-to-buy-ventilators-help-migrants-and-develop-a-vaccine/articleshow/75722737.cms",
    "work": "The Economic Times",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM-CARES ventilator row: Experts discuss order and procurement challenges",
    "url": "https://www.cnbctv18.com/healthcare/pm-cares-ventilator-row-experts-discuss-order-and-procurement-challenges-6279561.htm",
    "work": "cnbctv18.com",
    "date": "7 July 2020",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Only 6% ventilators under PM-CARES manufactured so far",
    "url": "https://indianexpress.com/article/india/only-6-ventilators-under-pm-cares-manufactured-so-far-6473172/",
    "work": "The Indian Express",
    "date": "2020-06-24",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Govt Panels Flag Issues With AgVa Ventilators Bought By PMCARES Fund",
    "url": "https://www.huffingtonpost.in/entry/agva-ventilators-pmcares-covid-19-order_in_5ef1ea38c5b6001a27157ccd",
    "work": "HuffPost India",
    "date": "2020-06-24",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Coronavirus — Ventilators from firms funded by PM CARES fail trials",
    "url": "https://www.thehindu.com/news/national/coronavirus-ventilators-from-firms-funded-by-pm-cares-fail-trials/article32416810.ece",
    "work": "The Hindu",
    "date": "2020-08-21",
    "accessDate": "2020-08-22"
  },
  {
    "title": "Company With No Ventilator Model Got Rs 373 Cr PM CARES Order To Make 10,000 Ventilators",
    "url": "https://www.huffingtonpost.in/entry/pmcares-ventilator-order-trivitron-healthcare_in_5f6c1122c5b6e2c91260f168",
    "work": "HuffPost India",
    "date": "2020-09-24",
    "accessDate": "2020-10-02"
  },
  {
    "title": "Coronavirus: Delhi's Lok Nayak Hospital flags key defect in ventilators supplied by Centre",
    "url": "https://scroll.in/latest/966197/coronavirus-delhis-lok-nayak-hospital-flags-key-defect-in-ventilators-supplied-by-centre",
    "work": "Scroll.in",
    "date": "July 2020",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PGI gets 10 ventilators through PM CARES fund, finds them faulty",
    "url": "https://indianexpress.com/article/cities/chandigarh/pgi-gets-10-ventilators-through-pm-cares-fund-finds-them-faulty-6522661/",
    "work": "The Indian Express",
    "date": "2020-07-25",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Despite doubts about 'low-end' machines, Karnataka to deploy 640 PM Cares ventilators",
    "url": "https://indianexpress.com/article/india/despite-doubts-about-low-end-machines-karnataka-to-deploy-640-pm-cares-ventilators-6517201/",
    "work": "The Indian Express",
    "date": "2020-07-22",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Karnataka Govt offer to loan PM Cares ventilators to private hospitals finds few takers",
    "url": "https://indianexpress.com/article/cities/bangalore/karnataka-govt-offer-to-loan-pm-cares-ventilators-to-private-hospitals-finds-few-takers-6673336/",
    "work": "The Indian Express",
    "date": "2020-10-03",
    "accessDate": "2020-10-07"
  },
  {
    "title": "Coronavirus: Ventilators given under PM-CARES fund are faulty, Rajasthan tells Centre",
    "url": "https://scroll.in/latest/991726/coronavirus-ventilators-given-under-pm-cares-fund-are-faulty-rajasthan-tells-centre",
    "work": "Scroll.in",
    "date": "8 April 2021",
    "accessDate": "2021-04-25"
  },
  {
    "title": "Pune: 17 ventilators received under PM-Care Fund gather dust at YCM hospital",
    "url": "https://indianexpress.com/article/cities/pune/17-ventilators-received-under-pm-care-fund-gather-dust-at-ycm-hospital-7267642/",
    "work": "The Indian Express",
    "date": "2021-04-10",
    "accessDate": "2021-04-25"
  },
  {
    "title": "Ventilators received under PM CARES lying unopened at civic hospitals: BJP",
    "url": "https://indianexpress.com/article/cities/mumbai/ventilators-received-under-pm-cares-lying-unopened-at-civic-hospitals-bjp-6507875/",
    "work": "The Indian Express",
    "date": "2020-07-16",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Fact check: Did states fail to use PM-Cares funds allocated by the Centre to build oxygen plants?",
    "url": "https://scroll.in/article/993309/fact-check-did-states-fail-to-use-pm-cares-funds-allocated-by-the-centre-to-build-oxygen-plants",
    "work": "Scroll.in",
    "date": "26 April 2021",
    "accessDate": "2021-04-27"
  },
  {
    "title": "India is running out of oxygen, Covid-19 patients are dying – because the government wasted time",
    "url": "https://scroll.in/article/992537/india-is-running-out-of-oxygen-covid-19-patients-are-dying-because-the-government-wasted-time",
    "work": "Scroll.in",
    "date": "18 April 2021",
    "accessDate": "2021-04-25"
  },
  {
    "title": "Only 33 oxygen generation plants built, of 162 sanctioned: Health ministry",
    "url": "https://www.theweek.in/news/india/2021/04/18/amid-oxygen-shortage-health-ministry-says-33-psa-plants-built-out-of-162-sanctioned.html",
    "work": "The Week",
    "date": "",
    "accessDate": "2021-04-25"
  },
  {
    "title": "Health Ministry tells HC only 1 of 8 oxygen plants sanctioned under PM CARES Fund set up in Delhi",
    "url": "https://www.indiatoday.in/coronavirus-outbreak/story/delhis-oxygen-plants-delayed-as-covid-patients-gasp-in-hospitals-1793600-2021-04-22",
    "work": "",
    "date": "April 22, 2021",
    "accessDate": "2021-04-25"
  },
  {
    "title": "COVID-19 surge: PM CARES Fund allocates funds for 551 oxygen plants in public health facilities",
    "url": "https://www.thehindu.com/news/national/covid-19-surge-pm-cares-fund-allocates-funds-for-551-oxygen-plants-in-public-health-facilities/article34406175.ece",
    "work": "The Hindu",
    "date": "2021-04-25",
    "accessDate": "2021-04-29"
  },
  {
    "title": "Coronavirus — PM CARES to fund 1 lakh portable oxygen concentrators",
    "url": "https://www.thehindu.com/news/national/covid-19-govt-to-procure-1-lakh-portable-oxygen-concentrators-from-pm-cares-fund/article34431100.ece",
    "work": "The Hindu",
    "date": "2021-04-28",
    "accessDate": "2021-04-29"
  },
  {
    "title": "PM CARES Fund Not A Public Authority Under RTI Act : Affirms Appellate Authority In PMO",
    "url": "https://www.livelaw.in/top-stories/pm-cares-funds-not-a-public-authority-under-rti-act-affirms-appellate-authority-in-pmo-159152",
    "work": "LiveLaw",
    "date": "2020-06-30",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Plea to declare PM CARES Fund as a 'public authority' under RTI not maintainable: PMO to Delhi HC",
    "url": "https://indianexpress.com/article/india/plea-to-declare-pm-cares-fund-as-a-public-authority-under-rti-not-maintainable-pmo-to-delhi-hc-6452582/",
    "work": "The Indian Express",
    "date": "2020-06-10",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PMO denies RTI plea seeking info on PM-CARES",
    "url": "https://www.thehindu.com/news/national/pmo-denies-rti-plea-seeking-info-on-pm-cares/article32369180.ece",
    "work": "The Hindu",
    "date": "2020-08-16",
    "accessDate": "2020-08-17"
  },
  {
    "title": "PM Cares website given govt internet domain name, reveals RTI; why so for a charitable trust, asks activist",
    "url": "https://www.indiatoday.in/india/story/pm-cares-domain-name-pmo-oct-2019-rti-reply-1730648-2020-10-12",
    "work": "India Today",
    "date": "October 12, 2020",
    "accessDate": "2020-10-13"
  },
  {
    "title": "Now PMO Stops Govt Depts from Sharing RTI Info on PM CARES Fund",
    "url": "https://www.thequint.com/news/india/pmo-stops-govt-departments-from-sharing-rti-info-on-pm-cares-fund",
    "work": "TheQuint",
    "date": "2020-10-13",
    "accessDate": "2020-10-13"
  },
  {
    "title": "Ex-bureaucrats flag 'clear lack of transparency' in PM Cares Fund",
    "url": "https://indianexpress.com/article/india/ex-bureaucrats-flag-clear-lack-of-transparency-in-pm-cares-fund-7149439/",
    "work": "The Indian Express",
    "date": "2021-01-17",
    "accessDate": "2021-01-18"
  },
  {
    "title": "Cabinet never discussed setting up of PM-CARES fund: RTI",
    "url": "https://www.deccanherald.com/national/cabinet-never-discussed-setting-up-of-pm-cares-fund-rti-876095.html",
    "work": "Deccan Herald",
    "date": "2020-08-21",
    "accessDate": "2020-08-22"
  },
  {
    "title": "Trustees of PM CARES appoint SARC & Associates as auditor of fund",
    "url": "https://www.business-standard.com/article/current-affairs/trustees-of-pm-cares-appoint-sarc-associates-as-auditor-of-fund-120061300060_1.html",
    "work": "Business Standard India",
    "date": "2020-06-13",
    "accessDate": "2020-07-30"
  },
  {
    "title": "PM CARES Fund Now Has 'Independent Auditor' But Remains Beset by Lack of Transparency",
    "url": "https://thewire.in/government/pm-cares-fund-now-has-independent-auditor-but-remains-beset-by-lack-of-transparency",
    "work": "The Wire",
    "date": "",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Delhi CA firm SARC to audit PM CARES fund- Business News",
    "url": "https://www.businesstoday.in/current/economy-politics/delhi-ca-firm-sarc-to-audit-pm-cares-fund/story/406536.html",
    "work": "www.businesstoday.in",
    "date": "10 June 2020",
    "accessDate": "2021-04-27"
  },
  {
    "title": "Chinese funds deposited into PM CARES on day of clash, says A.P Congress Committee president S. Sailajanath",
    "url": "https://www.thehindu.com/news/cities/Vijayawada/chinese-funds-deposited-into-pm-cares-on-day-of-clash-says-ap-congress-committee-president-s-sailajanath/article31942505.ece",
    "work": "The Hindu",
    "date": "2020-06-29",
    "accessDate": "2020-07-30"
  },
  {
    "title": "'Return Chinese firms' donations to PM CARES'",
    "url": "https://www.thehindu.com/news/national/other-states/return-chinese-firms-donations-to-pm-cares/article31949092.ece",
    "work": "The Hindu",
    "date": "2020-06-30",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Delhi Police books fraudsters for making fake SBI account of PM's Covid-19 Relief Fund",
    "url": "https://www.indiatoday.in/india/story/delhi-police-books-fraudsters-for-making-fake-sbi-account-of-pm-s-covid-19-relief-fund-1661272-2020-03-30",
    "work": "India Today",
    "date": "30 March 2020",
    "accessDate": "2020-03-30"
  },
  {
    "title": "PM CARES FUND fake UPI id scam: Make sure you donate to the correct ID",
    "url": "https://indianexpress.com/article/technology/tech-news-technology/pm-cares-fund-coronavirus-fund-fake-upi-id-scam-make-sure-you-donate-to-the-correct-id-6338460/",
    "work": "The Indian Express",
    "date": "2020-04-04",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Software engineer cheated of ₹28,000 under garb of PM Cares fund",
    "url": "https://www.thehindu.com/news/cities/mumbai/software-engineer-cheated-of-28000-under-garb-of-pm-cares-fund/article31435465.ece",
    "work": "The Hindu",
    "date": "2020-04-26",
    "accessDate": "2020-07-30"
  },
  {
    "title": "No transfer of money from PM CARES to disaster relief fund: SC",
    "url": "https://www.livemint.com/news/india/no-transfer-of-money-from-pm-cares-to-disaster-relief-fund-sc-11597732268728.html",
    "work": "Livemint",
    "date": "2020-08-18",
    "accessDate": "2020-08-18"
  },
  {
    "title": "[Breaking] SC Dismisses Plea To Transfer PM CARES Funds To NDRF; Says Fresh National Disaster Plan For COVID-19 Not Needed Read",
    "url": "https://www.livelaw.in/top-stories/sc-dismisses-plea-to-transfer-pm-cares-funds-to-ndrf-saysfresh-national-disaster-plan-for-covid-19-not-needed-161577",
    "work": "www.livelaw.in",
    "date": "2020-08-18",
    "accessDate": "2020-10-22"
  },
  {
    "title": "PM Cares Fund Run By Trusteeship Of Council Of Ministers Itself, Without Statutory Support U/A 53(3)(b): Review Plea In SC Against Dismissal Of PIL For Transferring Funds To NDRF Read",
    "url": "https://www.livelaw.in/top-stories/pm-cares-fund-run-by-trusteeship-of-council-of-ministers-review-plea-in-sc-against-dismissal-of-pil-for-transferring-funds-to-ndrf-163248",
    "work": "www.livelaw.in",
    "date": "2020-09-21",
    "accessDate": "2020-10-22"
  },
  {
    "title": "Misconceived Petition : SC Dismisses PIL Challenging PM CARES Fund",
    "url": "https://www.livelaw.in/top-stories/misconceived-petition-sc-dismisses-pil-challenging-pm-cares-fund-155174",
    "work": "livelaw.in",
    "date": "2020-04-13",
    "accessDate": "2020-04-13"
  },
  {
    "title": "Plea seeks declaration of amount received, spent by PM-CARES Fund",
    "url": "https://www.thehindu.com/news/national/plea-seeks-declaration-of-amount-received-spent-by-pm-cares-fund/article31582644.ece",
    "work": "The Hindu",
    "date": "2020-05-14",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Bombay HC's Nagpur bench issues notice to Centre over plea seeking details of PM CARES fund",
    "url": "https://indianexpress.com/article/india/bombay-hcs-nagpur-bench-issues-notice-to-centre-over-plea-seeking-details-of-pm-cares-fund-6439646/",
    "work": "The Indian Express",
    "date": "2020-06-03",
    "accessDate": "2020-07-30"
  },
  {
    "title": "Contributions Made To The Fund Are Voluntary, No Compulsion For Anyone To Donate; Bombay HC Dismisses Advocate's PIL Seeking Public Declaration Of PM Cares Fund Read",
    "url": "https://www.livelaw.in/news-updates/contributions-made-to-the-fund-are-voluntary-no-compulsion-for-anyone-to-donate-bombay-hc-dismisses-advocates-pil-seeking-public-declaration-of-pm-cares-fund-162051",
    "work": "www.livelaw.in",
    "date": "2020-08-27",
    "accessDate": "2020-10-22"
  },
  {
    "title": "Plea in Delhi High Court seeks to bring PM CARES Fund under RTI",
    "url": "https://www.thehindu.com/news/national/plea-in-delhi-hc-seeks-to-bring-pm-cares-fund-under-rti/article31746478.ece",
    "work": "The Hindu",
    "date": "2020-06-04",
    "accessDate": "2020-07-30"
  },
  {
    "title": "FIR against Sonia Gandhi over Congress' tweets, party demands withdrawal of 'mischievous' complaint",
    "url": "https://indianexpress.com/article/india/sonia-gandhi-fir-congress-tweets-pm-cares-karnataka-6420861/",
    "work": "The Indian Express",
    "date": "2020-05-22",
    "accessDate": "2020-07-30"
  },
  {
    "title": "HC raps DU prof. for plea against deduction for PM CARES fund",
    "url": "https://www.thehindu.com/news/cities/Delhi/hc-raps-du-prof-for-plea-against-deduction-for-pm-cares-fund/article31846892.ece",
    "work": "The Hindu",
    "date": "2020-06-17",
    "accessDate": "2020-07-30"
  },
  {
    "title": "APTEL Permits Party To Deposit Cost To NDRF After It Is Contended That PM Cares Is Not A Govt Fund Read",
    "url": "https://www.livelaw.in/news-updates/aptel-permits-party-to-deposit-cost-to-ndrf-after-it-contends-that-pm-cares-it-is-not-a-govt-fund-read-order-164577",
    "work": "www.livelaw.in",
    "date": "2020-10-16",
    "accessDate": "2020-10-22"
  },
  {
    "title": "Redditor makes game on PM CARES fund with Prime Minister Narendra Modi as the main character",
    "url": "https://www.moneycontrol.com/news/trends/redditor-makes-game-on-pm-cares-fund-with-prime-minister-narendra-modi-as-the-main-character-5863331.html",
    "work": "Moneycontrol",
    "date": "",
    "accessDate": "2020-10-13"
  },
  {
    "title": "Reddit user's take on Chrome dinosaur game pokes fun at PM-CARES",
    "url": "https://www.theweek.in/news/india/2020/09/20/reddit-users-satirical-chrome-dinosaur-game-pokes-fun-at-pm-cares.html",
    "work": "The Week",
    "date": "",
    "accessDate": "2020-10-13"
  },
  {
    "title": "Reddit User Develops 'PM Cares Fund Not Found' Game Mocking Economy, COVID-19, Etc.",
    "url": "https://in.news.yahoo.com/reddit-user-develops-pm-cares-185605697.html",
    "work": "in.news.yahoo.com",
    "date": "",
    "accessDate": "2020-10-13"
  }
]

export const seeAlso = [
  { label: "Prime Minister's National Relief Fund", url: 'https://en.wikipedia.org/wiki/PMNRF' },
  { label: 'COVID-Crypto Relief Fund', url: 'https://en.wikipedia.org/wiki/COVID-Crypto_Relief_Fund' },
]
